services:
  mysql:
    image: mysql:8.0
    container_name: interviewhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interviewsdatadatabase
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"   # local mysql irundhaa 3307
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./interviewhubs
    container_name: interviewhub-backend
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/interviewsdatadatabase
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_MAIL_USERNAME: rajikalaiselvan17@gmail.com
      SPRING_MAIL_PASSWORD: YOUR_NEW_APP_PASSWORD

  frontend:
    build: ./interviewhubDemo
    container_name: interviewhub-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data: